### ISSUE TITLE
Go+ release tool

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#1018]
### Proposal

- `go run cmd/make.go -tag <Version>`, it will automatically update the `VERSION` file in release branch and create a new tag  named `<Version>`. The release branch of `<Version = vMAJOR.MINOR.PATCH>` is `vMAJOR.MINOR`.

See https://github.com/goplus/gop/issues/817 for details.

### Background

none

### Workarounds

none

**Comment by 92hackers** [comment]
#1055
