### ISSUE TITLE
Support pure go+ module

### ISSUE THREAD

**Issue by cpunion** [goplus/gop#1056]
### Proposal

**1. Support import a pure go+ package in the current project**

E.g. a project structure like the below:
```shell
├── foo
│   └── foo.gop
├── go.mod
├── go.sum
├── gop.mod
└── main.gop
```

It should be possible to import the package `foo` from `main.gop` directly.

**2. Support import a pure go+ module on the GitHub**

It should be possible to `import "github.com/x/y"` or `import "github.com/x/y/z"`, when `github.com/x/y` is a pure go+ module, and the package `y` is a pure go+ package in it.

### Background

To develop a go+ project, we want to write pure go+ code everywhere, we also want to publish the pure go+ modules.

### Workarounds

**For the packages in your project**

Use https://github.com/cosmtrek/air to watch `*.gop` files changes, and run `gop build ./...`.

**For the packages from the other modules**

Nothing.

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v1.1.0-alpha2
