### ISSUE TITLE
Will gop code be loaded dynamically on go runtime in the future?

### ISSUE THREAD

**Issue by hemmmapart** [goplus/gop#1111]
### Proposal

I wonder whether go+ code would be loaded dynamically on go runtime in the future, I saw the example "14-Using-goplus-in-Go/gomain" is disappeared , hoping the update of README.md.

### Background

I got the demand to load plugins dynamically on go runtime, I don't want to involve other language like Lua or Javascript. After my investigation, I see that there is only an immature go runtime interpreter named yaegi , did go+ got a plan to do such a go runtime interpreter?

### Workarounds

yaegi addr: https://github.com/traefik/yaegi/

**Comment by xushiwei** [comment]
Supported already. See https://github.com/goplus/ispx as an example.

**Comment by xushiwei** [comment]
* [github.com/goplus/igop](https://github.com/goplus/igop) (suggest)
* [github.com/goplus/yaigop](https://github.com/goplus/yaigop) (use `yaegi` or other engine)
