### ISSUE TITLE
提一个很尖锐的问题

### ISSUE THREAD

**Issue by yjbdsky** [goplus/gop#1124]
### Proposal

增加中文文档

### Background

想安利go给基础差的同事，看到许大的文章说几岁的小朋友都会，然后过来一看，发现全是英文，这这这，让我还得给同事翻译英文。那我还是直接教go吧。
许大go+的宏远是让小孩子都会，但没有中文文档？文章说几岁的小孩子都会，我只能说那是许大教得好，你直接教go都能教会。(不喜勿喷)

### Workarounds

增加中文文档

**Comment by yjbdsky** [comment]
主要是看到许大的c2go文章来的，严重支持一下，顺便过来吐槽一下。

**Comment by minr** [comment]
我是支持中文文档的！

哈哈哈哈哈哈哈。

**Comment by deepdream88** [comment]
为什么没有一点中文含量，开发团队都是外国人吗？

**Comment by xushiwei** [comment]
中文站目前确定会通过公众号，官网还是global/英语为主。

**Comment by xushiwei** [comment]
https://github.com/uiuing/gop-translations_tutorial-zh-cn
