### ISSUE TITLE
2 Feature proposals

### ISSUE THREAD

**Issue by tzvikalet** [goplus/gop#1146]
### Proposal

Just met with this repository and seems very promising!
2 ideas that came to my mind that can be also cool if you would support in this language:

1. String interpolation with $ sign - like: `println ("num 1: $num, num2: ${num2*2}")`
2. enums support like: `enum Gender {male, female}` 
   and then we could use `var gender Gender` 
   and `gender := Gender.male`

### Background

just cool features than can be added, to make gop even more awsome

### Workarounds

for string interpolation: fmt.Sprintf
for enum this can be used in regular go: https://stackoverflow.com/questions/14426366/what-is-an-idiomatic-way-of-representing-enums-in-go

**Comment by xushiwei** [comment]
`${expr}` supported (see https://github.com/goplus/gop/releases/tag/v1.2.0-pre.2)
and `enum` is not planed.
