### ISSUE TITLE
希望GO+能够解决 go因为处理并发问题使得代码可读性变得复杂

### ISSUE THREAD

**Issue by LIngMax** [goplus/gop#1217]
### Proposal

go+优化很不错 这让我看到了  go代码可读性变简单解决方案
我们正在寻找一种能让 (全局变量并发没有竞争的读写方式)

### Background

目前我们的并发解决方案都是有问题的 
项目大了 问题越堆越多

方案1  通常是加锁  但是这种方式会极大影响代码可读性  特别是涉及if作用域里
mutexb.Lock()
mutexb.Unlock()
这种方案使得我们百万行项目代码变得极其复杂   而且漏加就会造成报错闪退结果 
这样的稳定性是我们不能接受的  要知道没有人不犯错误   很难审计
甚至有想过切换到nodejs 毕竟它稳定 虽然他占用内存cg很糟糕

方案2  runtime.GOMAXPROCS(1) //单线程
这种方式会影响到cpu多核利用 我们使用多开进程方式也能达到目的
并发读写全局变量会造成报错闪退结果  比多核出现的概率小80%左右  但是依旧存在少量并发竞争闪退

### Workarounds

我们希望GO+ 能够增加一种 读写全局变量自动的加锁方式  避免失误原因导致并发闪退

或者类似这种增加并发稳定性的 解决方案
runtime.GOMAXPROCS(1) //单线程

**Comment by xushiwei** [comment]
不建议大量使用全局变量，这比较违背 Go 的最佳实践。所以可能你们最应该讨论是如何明确服务的构建模式。
