### ISSUE TITLE
command style invalid operation mismatched types

### ISSUE THREAD

**Issue by visualfc** [goplus/gop#1312]
### The following program `sample.gop` triggers an unexpected result

```go
// add a sample
println (1+2i)*2
```

### Expected result

```console
2+4i
```

### Got

```console
invalid operation: println (1+2i)*2 (mismatched types (n int, err error) and untyped int)
```

### Gop Version

gop v1.1.2

### Additional Notes

```go
println((1+2i)*2) // is ok
```

_No response_

**Comment by xushiwei** [comment]
bug or not bug? need to make a decision.

**Comment by xushiwei** [comment]
consider as a bug.
