### ISSUE TITLE
unable to install goplus on ubuntu 20.04

### ISSUE THREAD

**Issue by mukunda7** [goplus/gop#1349]
### The following program `sample.gop` triggers an unexpected result

```coffee
// add a sample
/usr/local/go/gop/all.bash
```

### Expected result

```console
a clean installation, but received  Exit status 1
```

### Got

```console
+ go run cmd/make.go --install --autoproxy
2022/11/29 16:56:43 Error: must be a git repo or a VERSION file existed.
exit status 1
```

### Gop Version

1.1.3

**Comment by xushiwei** [comment]
please download source code from https://github.com/goplus/gop/releases and then run all.bash.

**Comment by chenrui333** [comment]
or you can just do `brew install goplus`
