### ISSUE TITLE
Question: Is there a way to run gop in watch mode?

### ISSUE THREAD

**Issue by StephanSchmidt** [goplus/gop#1424]
### Proposal

Is there a way to run Go+ in watch mode? So everytime one .gop file is changed it is transpiled to a .go file?

### Background

This would keep the speed of go compilations when you compile go code, the step of transpiling .gop to .go would go away.

### Workarounds

Use the current one-sweep .gop to go transpiling.

**Comment by xushiwei** [comment]
Usage:

```
gop watch [-v -gentest] [dir]
```

**Comment by StephanSchmidt** [comment]
Thank you very much, astonishing development speed!
