### ISSUE TITLE
About v1.2.0-pre.1 release

### ISSUE THREAD

**Issue by chenrui333** [goplus/gop#1611]
👋 QQ is [v1.2.0-pre.1](https://github.com/goplus/gop/releases/tag/v1.2.0-pre.1) a pre-release or a stable release? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/159264

**Comment by xushiwei** [comment]
It's a pre-release, but should be stable in most case.

**Comment by xushiwei** [comment]
done

**Comment by chenrui333** [comment]
Thank you!

**Comment by chenrui333** [comment]
> What I'm saying is that I don't see any evidence that upstream creates releases using a stable tag (e.g., 1.2.3) and marks it as "pre-release" before it's stable/released (removing the "pre-release" status when it's released). That's what the livecheck block comment is explaining but that isn't the situation in this repository (unlike the other formulae using this comment).

> Looking back at [previous snapshots of the GitHub releases page](https://web.archive.org/web/20221001000000*/https://github.com/goplus/gop/releases), the issue is that upstream creates GitHub releases for unstable versions (e.g., v1.2.0-pre.1, v1.1.0-rc3, v1.1.0-alpha3) without marking them as pre-release. In this scenario, if upstream doesn't reliably mark unstable releases as "pre-release", GithubLatest may return an unstable version or an Unable to get versions error. Like you, I don't have much faith that upstream will reliably mark unstable releases as "pre-release" (like they've done for v1.2.0-pre.1) going forward.

> As mentioned above, checking the Git tags using the standard regex 1) avoids unstable versions and 2) won't run into any issues with upstream's poor irregular process (i.e., failing to mark an unstable release as "pre-release" won't affect livecheck's output). I agree that upstream isn't careful about releases but the solution is to check the Git tags using a stricter regex (to avoid the v1.2.0-pre.1 tag). GithubLatest isn't appropriate in this context and it's likely to lead to further issues rather than fixing this.

Add @samford's comment for the future ref. 🙏
