### ISSUE TITLE
call small letter method by define order

### ISSUE THREAD

**Issue by visualfc** [goplus/gop#1663]
### The following program `sample.gop` triggers an unexpected result

```coffee
// add a sample
type point struct {
	x int
	y int
}

func (p *point) Demo() {
	println "call Demo"
}

func (p *point) demo() {
	println "call demo"
}

func (p *point) demo2() {
	println "call demo2"
}

func (p *point) Demo2() {
	println "call Demo2"
}

pt := &point{}
pt.demo()
pt.demo2()
```

### Expected result

```console
call demo
call demo2
```

### Got

```console
call Demo
call demo2
```

### Gop Version

gop v1.1.3

### Additional Notes
code  demo
https://play.goplus.org/p/KVDLZVkwNvf

**Comment by xushiwei** [comment]
I think it is better to report an error (cannot tell whether to call demo or Demo).
