### ISSUE TITLE
Missed page https://github.com/goplus/gop/blob/main/doc/dsl-vs-sdf.md on homepage

### ISSUE THREAD

**Issue by BaseMax** [goplus/gop#1771]
Missed page https://github.com/goplus/gop/blob/main/doc/dsl-vs-sdf.md on homepage

https://goplus.org/

> 404 - page not found
doc/dsl-vs-sdf.md.

**Comment by xushiwei** [comment]
We may refactor the homepage.

**Comment by nighca** [comment]
First we fix the outdated links (and text content). Next we check if there is structral change and refactoring is needed.

**Comment by nighca** [comment]
It is ok to close this issue now.
