### ISSUE TITLE
Var definition

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#276]
- Support global scope var definition.
- Support block scope var definition.

**Comment by 456vv** [comment]
ctx := exec.NewContext(code)
    ctx.Go(0, func(goctx *exec.Context){
                //这想在这里定义一个局部变量
                //因为使用parser.Parse解析过来的，没有设置DefineVar
                //以下代码会发生错
		//xt := reflect.TypeOf(&in).Elem()
		//x := exec.NewVar(xt, "T")
		//goctx.SetVar(x, in)
		goctx.Run()
	})

**Comment by xushiwei** [comment]
https://github.com/goplus/gox/releases/tag/v0.6.0
