### ISSUE TITLE
Jupyter and nteract support

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#314]
See:
* https://github.com/gopherdata/gophernotes
* https://github.com/yunabe/lgo

**Comment by wangfenjin** [comment]
Hi @xushiwei ,

I'm interested in implement this feature. After look into the codebase, I think we should based on gophernotes and create a new repo for that, because the evaluation logic is different from the original codebase.

What you think?

**Comment by wangfenjin** [comment]
I had implement the initial version, you can try here: https://github.com/wangfenjin/gopyter

**Comment by xushiwei** [comment]
cool!

**Comment by xushiwei** [comment]
fork: https://github.com/goplus/gopyter
