### ISSUE TITLE
cmd/qexp: export types, vars and constants

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#340]

**Comment by visualfc** [comment]
assign @visualfc

**Comment by xushiwei** [comment]
export vars and constants - https://github.com/qiniu/goplus/pull/373

**Comment by JessonChan** [comment]
go package vars still can't be used
```go
import "flag"
println(flag.Usage)
```
will panic

> goplus/cl/expr.go:915: compileSelectorExpr: unknown GoPackage symbol kind - 0
> panic: compileSelectorExpr: unknown GoPackage symbol kind - 0

**Comment by visualfc** [comment]
> go package vars still can't be used
> 
> ```go
> import "flag"
> println(flag.Usage)
> ```
> 
> will panic
> 
> > goplus/cl/expr.go:915: compileSelectorExpr: unknown GoPackage symbol kind - 0
> > panic: compileSelectorExpr: unknown GoPackage symbol kind - 0

这是因为目前还不支持 gopkg var 读写的原因

**Comment by xushiwei** [comment]
See https://github.com/qiniu/goplus/pull/293
It is still under reviewing.
