### ISSUE TITLE
vscode-goplus

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#352]
The VS Code Go Extension Joins The Go Project: https://blog.golang.org/vscode-go
How about vscode-goplus?

**Comment by go-wyvern** [comment]
[DOING](https://github.com/go-wyvern/vscode-goplus)

**Comment by xushiwei** [comment]
This maybe is a big feature and need to split into many small enhancements so that you can make pull request frequently.
I think a brief design will make make things smoothly.

**Comment by xushiwei** [comment]
@visualfc is author of liteide. He have many experience about go plugin of ide.
We can share our ideas about this issue.

**Comment by go-wyvern** [comment]
https://github.com/go-wyvern/vscode-goplus

now support:

 - Syntax Highlight
 - Auto Snippet
 - Format Source Code
 - Auto Completion
 - Hover function Display
 - Auto import
 - Show Definitions of a Symbol

It is currently implemented using go’s toolchain, and after the completion of gopls, it will switch to the language server

**Comment by go-wyvern** [comment]
> @visualfc is the author of liteide. He have many experience about go plugin of ide.
> We can share our ideas about this issue.

I know visualfc and I am very happy to complete gopls with him

**Comment by xushiwei** [comment]
@go-wyvern create a pull request?

**Comment by xushiwei** [comment]
https://github.com/gopcode/vscode-goplus
