### ISSUE TITLE
Import Go+ package in  Go+ project

### ISSUE THREAD

**Issue by blueway** [goplus/gop#378]
main.gop
```go
import (
   	"github.com/qiniu/goplus/tutorial/14-Using-goplus-in-Go/foo"
)
 
b := foo.reverseMap(s)
println(b)
```

`qrun main.gop`

output:
`panic: compileIdent failed: package not found - github.com/qiniu/goplus/tutorial/14-Using-goplus-in-Go/foo
`

How to import Go+ package in Go+ project?

So i must install the `foo` package using `go get  github.com/qiniu/goplus/tutorial/14-Using-goplus-in-Go/foo`,

**Comment by xushiwei** [comment]
Not implemented yet.

**Comment by xushiwei** [comment]
Related issue: #472

* Support export Github packages.
* Support export GoPlus src packages.

See #473
See https://github.com/goplus/gop/wiki/Import-Go-packages-in-GoPlus-programs

Currently, we only support to import a Go package statically.

**Comment by myml** [comment]
```bash
cd $GoPlusRoot
qexp <goPkgPathToImport>
cd lib/default.go
vim lib/default.go
# add <goPkgPathToImport> and save  描述并不准确，我在这里费了一些时间，直到我跟踪了gop的源码才了解，建议替换为
# add github.com/goplus/gop/lib/<goPkgPathToImport> and save
go install -v ./...
```

**Comment by xushiwei** [comment]
> ```shell
> cd $GoPlusRoot
> qexp <goPkgPathToImport>
> cd lib/default.go
> vim lib/default.go
> # add <goPkgPathToImport> and save  描述并不准确，我在这里费了一些时间，直到我跟踪了gop的源码才了解，建议替换为
> # add github.com/goplus/gop/lib/<goPkgPathToImport> and save
> go install -v ./...
> ```

thx
