### ISSUE TITLE
In programs with a main() function, do not support non-declaration top-level statements.

### ISSUE THREAD

**Issue by lolbinarycat** [goplus/gop#412]
go+ allows instructions to be at top level, so a program like this is valid:
```
println("hello")
```

this is reasonable, as it allows small projects to write less code to get started.
currently, a program like this will not compile:
```
println("hello")
func main() {
    println("goodbye")
}
```
**This is good**. For one, I am often alerted to a mistake by `syntax error: non-declaration statement outside function body`. Far more important though, is readability. larger projects will likely have `func main()` to group all of their code that runs at the start together. You should be able to look in `main()` and see all of the code that will run. Otherwise ypu would have to check every file.

**Comment by xushiwei** [comment]
In the Go+ language, we allow that only one .gop file exists global statements.
