### ISSUE TITLE
Does Goplus currently only support single-word dependency packages ?

### ISSUE THREAD

**Issue by Kuri-su** [goplus/gop#420]
* gop version: master(v0.6.60+)
* go version: 1.14

I'm write a simple demo about json encode

```go
// t.gop
package main

import "encoding/json"

func main() {
	a := {
		"Hello": {"Hello": 1, "xsw": "Go+"},
		"xsw":   3.4,
	}
	marshal, err := json.Marshal(a)
	if err != nil {
		panic(err)
	}

	println(string(marshal))
}
``` 
```shell
$ qrun t.gop
```

but it say this: 
```shell
[PANIC] /tmp/goplus/cl/expr.go:163: compileIdent failed: package not found - encoding/json
panic: compileIdent failed: package not found - encoding/json
```

maybe this is a same issue with #378 && #411 ?

> thanks for you and your hand work :)

**Comment by Kuri-su** [comment]
ok, i got it , currently only support these package, 

* github.com/qiniu/x/errors/
* flag
* fmt
* io
* io/ioutil
* log
* os
* reflect
* strconv
* strings
* sync
* sync/atomic

How to support more libraries, maybe we can contribute with this part ; )

**Comment by jiangz222** [comment]
> ok, i got it , currently only support these package,
> 
> * github.com/qiniu/x/errors/
> * flag
> * fmt
> * io
> * io/ioutil
> * log
> * os
> * reflect
> * strconv
> * strings
> * sync
> * sync/atomic
> 
> How to support more standard libraries, maybe we can contribute with this part ; )

`qexport encoding/json`  may be your answer? 
After that, you have to rebuild qrun to make it work.

**Comment by xushiwei** [comment]
`qexp encoding/json`

**Comment by xushiwei** [comment]
See https://github.com/goplus/gop/wiki/Import-Go-packages-in-Go--programs
