### ISSUE TITLE
 goroutine compile error?

### ISSUE THREAD

**Issue by zct** [goplus/gop#433]
`
j := 0

arr := [1, 3, 5, 7, 11, 13, 17]

 i := 0
 for i = 0; i < len(arr); i++ {
     go func () {
  for  j = 0; j < len(arr); j++ {
     println(j)
 }
 }()
 }
`

use qrun  compile this program, get error information

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/issues/277

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/pull/524
