### ISSUE TITLE
Use "in" or "range" to replace "<-"

### ISSUE THREAD

**Issue by codinl** [goplus/gop#469]
1. "<-" spelling unnatural and poor readability.
2. "<-" looks like an operator，not a keyword. In this condition, keyword is better.
3. "for...in/range..", keywords appear in pairs, compares to "for ... <- ...", looks more natural.
4. "<-" is not common in other program languages.

"<-" should be abandoned to reduce complexity and misunderstanding.

**Comment by xushiwei** [comment]
duplicate with https://github.com/goplus/gop/issues/295
