### ISSUE TITLE
Go+ Console

### ISSUE THREAD

**Issue by JessonChan** [goplus/gop#479]
Go+ interactive console should provide programmers with a quick way to execute go+ code and try out or test code without creating file,running gop command. With all of Go+ built-in functions and libraries,Go+ console offers the opportunity to explore Go+ world and the abliity to paste code into files when the code is ready.

**Comment by xushiwei** [comment]
Related resource:
* https://github.com/go-python/gpython/tree/master/repl
* https://gpython.org/

**Comment by xushiwei** [comment]
TODO: Web REPL - https://github.com/goplusjs/repl

**Comment by visualfc** [comment]
https://github.com/goplusjs/repl/pull/1 for web REPL

**Comment by xushiwei** [comment]
https://repl.goplus.org/
