### ISSUE TITLE
Syntax Support: Python's generator pattern

### ISSUE THREAD

**Issue by wangkuiyi** [goplus/gop#519]
Python's generator pattern is a frequently-used one in deep learning, e.g., to load minibatches from a data loader.

The following line appears in EVERY PyTorch program:

```python
for i, data in enumerate(dataloader, 0):
```

Could Go+ support the generator pattern in the syntax like the following

```go
for data := range dataloader
```

by translating the above line into the following Go code snippet

```go
for data, ok := dataloader.Next(); ok; data, ok = dataloader.Next() {
````

if dataloader implements an interface
```go
type Generator interface {
     Next() (interface{}, bool)
}
```

To verify and better illustrate my idea, I wrote the following runnable program.

```go
package main

import (
	"fmt"
)

type Generator interface {
	Next() (interface{}, bool)
}

type Tensor struct {
	w, h int
}

func NewTensor(w, h int) *Tensor {
	return &Tensor{w, h}
}

type MyGenerator struct {
	i int
}

func NewMyGenerator() *MyGenerator {
	return &MyGenerator{0}
}

func (m *MyGenerator) Next() (interface{}, bool) {
	m.i++
	if m.i < 10 {
		return []*Tensor{
			NewTensor(10, 100),
			NewTensor(100, 1000)}, true
	}
	return nil, false
}

func trainModel(data []*Tensor) {
	fmt.Println(data)
}

func main() {
	g := NewMyGenerator()
	// In Go+, I hope the following line could be
	// for b := range g {
	for b, ok := g.Next(); ok; b, ok = g.Next() {
		trainModel(b.([]*Tensor))
	}
}
```

You can run it in Go Playground at https://play.golang.org/p/phuzyDJ4ZCg

**Comment by lolbinarycat** [comment]
At first I didn't like this, but now I think I understand it better, and it seems fine.

Basically you are proposing that the `range` keyword works on anything with a Next() function? To be clear this isn't python's enumerate function (as far as I can tell), which is already the default behavior of `range`. If performance isn't a huge concern, you could implement a function for this with generics:
```go
 package main

import (
	"fmt"
)

type Generator[type T] interface {
	Next() (T, bool)
}

func ReadAll[type T](g Generator[T]) []T {
	var arr = make([]T,0,10)
	for {
		itm, ok := g.Next()
		if !ok {
			return arr
		}
		arr = append(arr,itm)
	}
	
}

type IntGen struct {
	I int
	Max int
}

func (g *IntGen) Next() (int,bool) {
	g.I++
	if g.I < g.Max {
		return g.I, true
	}
	return 0, false
}

func main() {
	gen := IntGen{0,10}
	for _, v := range ReadAll[int](&gen) {
		fmt.Println(v)
	}
}
```

**Comment by xushiwei** [comment]
https://github.com/goplus/gop#for-range-of-udt
