### ISSUE TITLE
Parsing ambiguity: `<-` operator overloaded

### ISSUE THREAD

**Issue by lolbinarycat** [goplus/gop#530]
adding the ability to iterate over things with the `<-` operator overloads it, as that is the operator used for channel operations.
This seems like a poor choice honestly, because of 2 reasons:
1. there is already a syntax for iterating over things, and it is `:= range`
2. there are plenty of *unused* 2 character operators, one of those would work fine.
~~channels seem to be implemented, but trying to do anything with them results in a segfault~~ Well, on the other playground they don't work I don't know what's up with that.

**Comment by xushiwei** [comment]
I have answered this question in https://github.com/goplus/gop/issues/295.
