### ISSUE TITLE
Implement remaining go features before adding new major features.

### ISSUE THREAD

**Issue by lolbinarycat** [goplus/gop#531]
In the readme it says all goplus programs will be valid go programs. This is still not the case. Making this the case should be the case should be the main priority. Already features have been implemented that conflict with core go features (see #530 for an example). I worry that features are being added too quickly, and without enough consideration. Already I have trouble reading many of the examples, and that is one of go's biggest strengths.

**Comment by xushiwei** [comment]
Yes, we definitely think implementing go features is more important than implementing new go+ features. And almost all existing go+ features are implemented for telling people what go+ looks like.
