### ISSUE TITLE
#!/usr/bin/env qrun 的代码有办法编译成可执行文件吗？ 另外.go文件以#!/usr/bin/env qrun开头vim会提示语法检查错误，有什么解决方案吗？

### ISSUE THREAD

**Issue by gcxfd** [goplus/gop#561]
#!/usr/bin/env qrun 的代码有办法编译成可执行文件吗？

另外.go文件以#!/usr/bin/env qrun开头vim会提示语法检查错误，有什么解决方案吗？

![](https://user-images.githubusercontent.com/69608605/90715549-23883400-e2dd-11ea-94eb-41a828976a3c.png)

**Comment by xushiwei** [comment]
You can do the following steps to generate executable binary app:

```bash
cd <theDirectoryOfYourApp>
gop go .
go install .   # Or: go build .
```

See https://github.com/goplus/gop/issues/453.

> 另外.go文件以#!/usr/bin/env qrun开头vim会提示语法检查错误，有什么解决方案吗？

Use .gop as file extension.
