### ISSUE TITLE
xushiwei

### ISSUE THREAD

**Issue by welcome112s** [goplus/gop#630]
Go语言编程 书籍一处代码编程错误，

最近在看你的go 语言书籍 【Go语言编程】 看到了一处错误，
在第一章节的1.6 问题追踪与调试  

![image](https://user-images.githubusercontent.com/11868709/100421925-48eac200-30c4-11eb-9ef6-c3d08560eba4.png)

下面是正确的输出： 

The value of fval is 110.48
fval=110.480000, ival=200, sval=This is a string. 
fval=110.48, ival=200, sval=This is a string.

**Comment by xushiwei** [comment]
thx.
