### ISSUE TITLE
”gop export“ generate *_export.go:247:32: undefined: gop.ToInts

### ISSUE THREAD

**Issue by 456vv** [goplus/gop#634]
gop "github.com/goplus/gop"

No gop.ToInts function

**Comment by 456vv** [comment]
Only see:

    func ToBools(args []interface{}) []bool
    func ToError(v interface{}) error
    func ToStrings(args []interface{}) []string

more type need add!

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v0.9.3
