### ISSUE TITLE
"gop export" errir export "github.com/xx/yy" error: 25:91: expected ')', found '/'

### ISSUE THREAD

**Issue by 456vv** [goplus/gop#635]
export "github.com/xx/vweb/yy" error: 25:91: expected ')', found '/'
export "github.com/xx/vweb/yy" error: empty exported package

occurred error:

	type ServerTLSFile struct {
	    CertFile, KeyFile   string
	}
	func (T *ServerHTTP) LoadTLS(config *tls.Config, files []ServerTLSFile) error {
		...
	}

no error:

	type ServerTLSFile struct {
	    CertFile, KeyFile   string
	}
	func (T *ServerHTTP) LoadTLS(config *tls.Config, files []*ServerTLSFile) error {
		...
	}

problem is  ```[]ServerTLSFile``` not recognized

**Comment by 456vv** [comment]
types.Type 内部是以pkg.Path路径来生成做库名。造成后面无法正常的验证代码。所以报错。
文件地址：github.com\goplus\gop\cmd\internal\export\gopkg\exporter.go
可以这样修复它，或许你有更好方法，原因我不是很了解你们的代码：
```
func (p *Exporter) typeString(typ types.Type) string {
	if typNamed, ok := typ.(*types.Named); ok {
		typName := typNamed.Obj().Name()
		objPkg := typNamed.Obj().Pkg()
		if objPkg == nil {
			return typName
		}
		pkgName := objPkg.Name()
		return pkgName+"."+typName
	}
	typStr := typ.String()
	if !strings.Contains(typStr, ".") {
		return typStr
	}
	return p.fixPkgString(typ.String())
}
```

**Comment by 456vv** [comment]
这样很好：
```
func (p *Exporter) typeString(typ types.Type) string {
	typStr := types.TypeString(typ, func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		return pkg.Name()
	})
	return typStr
}
```

**Comment by 456vv** [comment]
```
func (p *Exporter) typeString(typ types.Type) string {
	typStr := types.TypeString(typ, func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		if name, ok := p.imports[pkg.Path()]; ok {
			return name
		}
		fmt.Printf("imports list -not find '%s', used by default name '%s'\n", pkg.Path(), pkg.Name())
		return pkg.Name()
	})
	return typStr
}
```

**Comment by visualfc** [comment]
建议提交 pull request，以便集成测试。

**Comment by 456vv** [comment]
#638 这里文件已经修复gop export 错误。已测正常。

```
type A interface{
    error
}
```

不完美的地方就是会导出：
```
error.Error
A.Error
```
不过不影响使用，对你们项目代码流程不熟悉，暂免 pull request，你们自己处理一下吧。

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v0.9.3
