### ISSUE TITLE
"gop export" unable to export interface, error occurred: compileSelectorExpr: method not found - (Responser).Error

### ISSUE THREAD

**Issue by 456vv** [goplus/gop#638]
patch file path: github.com/goplus/gop/cmd/internal/export/gopkg/export.go
patch file path: github.com/goplus/gop/cmd/internal/export/gopkg/exporter.go

[gopkg.zip](https://github.com/goplus/gop/files/5741388/gopkg.zip)

fixed import library name and error interface type

**Comment by xushiwei** [comment]
Can you create a pull request?

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v0.9.3
export is no longer needed.
