### ISSUE TITLE
'for' syntax execution error

### ISSUE THREAD

**Issue by 456vv** [goplus/gop#641]
原因是 ```value``` 变量是 ```nil```，无法将 ```i.Value()``` 设置给```value```。
默认的 ```l``` 是 ```nil```， 它没有初始化为 &log.Logger{}。
exec code:
```
func Value(i Iterator, value interface{}) {
	reflect.ValueOf(value).Elem().Set(i.Value())
}
```

occurred error:
```
ls := []*log.Logger{
    &log.Logger{},
    &log.Logger{},
}
for index, l := range ls {
    log.Println(index, l)
}
```

no errors:
```
ls := []log.Logger{
    log.Logger{},
    log.Logger{},
}
for index, l := range ls {
    log.Println(index, l)
}
```

**Comment by damonchen** [comment]
@456vv could you put the `for` test code here?

**Comment by 456vv** [comment]
I know the problem, I didn't solve it. repairing this unfamiliar project will take a lot of time. you guys are different, know how to fix it.

**Comment by visualfc** [comment]
fixed by master

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v0.9.3
