### ISSUE TITLE
exec/bytecode bug: swap struct slice element

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#645]
In bytecode mode (https://jsplay.goplus.org/):

```go
type student struct {
    name	string
    age		int
    score	int
}

a := [student{"A", 13, 90}, student{"B", 12, 72}, student{"C", 12, 85}]
a[1], a[2] = a[2], a[1]

println(a)
```

It got:

```
[{A 13 90} {B 12 72} {B 12 72}]
```

But int slice is good:

```go
a := [1, 3, 2]
a[1], a[2] = a[2], a[1]

println(a)
```

It got:

```
[1 2 3]
```

**Comment by visualfc** [comment]
this bug only for gopehrjs build version.

**Comment by visualfc** [comment]
fixed https://github.com/goplusjs/gopherjs/issues/8
update gopherjs to v1.1.6 and rebuild

**Comment by xushiwei** [comment]
@qiukeren please update https://jsplay.goplus.org/

**Comment by visualfc** [comment]
check fixed, https://jsplay.goplus.org/ auto updated.
