### ISSUE TITLE
Can it embed into golang as script engine to compile and run the script?

### ISSUE THREAD

**Issue by zhengzepeng** [goplus/gop#673]
Can it embed into golang as script engine to compile and run the script?

**Comment by zhengzepeng** [comment]
Now i know how to embed it into golang as a script engine, but i saw the notice , it can't be used in production environment.
Do you have any plan ? When will it be ready for production? Hope to Reply.

**Comment by xushiwei** [comment]
Yes, you can.
See https://github.com/goplus/gop/blob/master/cmd/internal/run/run.go
