### ISSUE TITLE
Feature Request: combination permutation like in Ruby

### ISSUE THREAD

**Issue by kokizzu** [goplus/gop#692]
In Ruby we can do this:
https://apidock.com/ruby/Array/combination
https://apidock.com/ruby/Array/permutation

If Go+ have this, I could completely ditch Ruby XD

**Comment by rainydew** [comment]
is this one suitable for you?
https://github.com/yanatan16/itertools

a golang implement of lib itertools in Python

**Comment by xushiwei** [comment]
It seems a feature request to a Go+ library, not to the language.
