### ISSUE TITLE
希望实现go的热更新功能，对整个go游戏行业都是巨大的推动和发展

### ISSUE THREAD

**Issue by 15951836388** [goplus/gop#698]
现在用go做游戏服务器，最大的问题，就是没有热更新。虽然有一些方案，但是都不太好。

看了下范例里，似乎是用go+生成go脚本，这没多大用。

理想情况：开发时，完全用go开发。发布时，把需要热更的go代码，全部移到go+部分里（不行的话，就生成go+的脚本），实现热更新， 无缝兼容

如果实现了，就堪比lua对游戏的影响。对go语言的发展也是大大的利好。

谢谢

**Comment by 456vv** [comment]
go plugin 标准库
