### ISSUE TITLE
Is goplus.org open source? The page has examples looks not correct.

### ISSUE THREAD

**Issue by liufuyang** [goplus/gop#699]
Some example there seems wrong (`array` and `arr`):
<img src="https://user-images.githubusercontent.com/161689/115109933-faf23000-9f78-11eb-8150-7bb69ed3506f.png" height="300">
Also buttons doesn't look the same color.
<img src="https://user-images.githubusercontent.com/161689/115109940-034a6b00-9f79-11eb-8ed2-e58da374dd0d.png" height="300">

If the goplus.org is open source then perhaps I can help fix, or?

**Comment by JessonChan** [comment]
here is the repo https://github.com/goplus/www

**Comment by qiukeren** [comment]
@liufuyang 

fixed.

https://github.com/goplus/www was just source code for goplus playground,

goplus.org is a simple static site just contains two files: `index.html`,`logo.svg`, but not in github.

之前goplus/www中只有playground的源码，没有goplus.org的源码。

now goplus.org source code is in pr https://github.com/goplus/www/pull/16

已经提pr上传代码。
