### ISSUE TITLE
export nonsupport types.Signature

### ISSUE THREAD

**Issue by jiufang171** [goplus/gop#703]
F:\work\ws-feature\gop>gop export github.com/chromedp/chromedp
go: finding module in C:\Users\XXX\go\pkg\mod\github.com\chromedp\chromedp@v0.6.10
panic: interface conversion: types.Type is *types.Signature, not *types.Named

goroutine 1 [running]:
github.com/goplus/gop/cmd/internal/export/gopkg.exportTypeName(0xc0003b9c00, 0xc002c4e4b0, 0xc000019a70, 0xd)
        C:/Users/aihao/go/pkg/mod/github.com/goplus/gop@v0.7.19/cmd/internal/export/gopkg/export.go:46 +0x128
github.com/goplus/gop/cmd/internal/export/gopkg.ExportPackage(0xc00053ef00, 0x152fc20, 0xc00046cd80, 0xc0000ae100, 0x3e)
        C:/Users/aihao/go/pkg/mod/github.com/goplus/gop@v0.7.19/cmd/internal/export/gopkg/export.go:240 +0x3ae
github.com/goplus/gop/cmd/internal/export.exportPkg(0xc000090120, 0x1c, 0xc0000ae100, 0x3e, 0xc00010fe00, 0x1, 0x1)
        C:/Users/aihao/go/pkg/mod/github.com/goplus/gop@v0.7.19/cmd/internal/export/export.go:200 +0x1b6
github.com/goplus/gop/cmd/internal/export.runCmd(0x179af00, 0xc00002a0a0, 0x1, 0x2)
        C:/Users/aihao/go/pkg/mod/github.com/goplus/gop@v0.7.19/cmd/internal/export/export.go:111 +0x1c7
main.main()
        C:/Users/aihao/go/pkg/mod/github.com/goplus/gop@v0.7.19/cmd/gop/main.go:76 +0x20b

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v0.9.3
