### ISSUE TITLE
lack check for duplicate case in switch

### ISSUE THREAD

**Issue by visualfc** [goplus/gop#721]
Go+ code
```
i5 := 5
switch i5 {
case 5:
    println("case 5")
case 5:
    println("case 5")
}
```
must check for duplicate case 5 in switch

**Comment by JessonChan** [comment]
In golang, `switch` statement runs the first case whose value is equal to the `case` expression.It might seem not so necessary to have the duplicate check.  Following example is legal.
```go
package main

func main() {
	a := 0
	b := 1
	switch a {
	case 0:
	case b - 1:
	}
}
```

**Comment by visualfc** [comment]
https://golang.google.cn/ref/spec#Switch_statements

Implementation restriction: A compiler may disallow multiple case expressions evaluating to the same constant. For instance, the current compilers disallow duplicate integer, floating point, or string constants in case expressions.
