### ISSUE TITLE
用gop做go的内嵌脚本

### ISSUE THREAD

**Issue by lx217197** [goplus/gop#736]
您好！
我是从qlang了解的这个项目，并且在知乎上看到gop可以做go的内嵌脚本使用，但是我有几个疑问。
1.qlang是gop的历史版本，如果我使用一个项目做go的内嵌脚本的话，我现在应该使用qlang还是gop?
2.qlang吸引我的地方在于，可以从go像qlang传递复杂的结构体，并且直接调用，gop可以做到这一点吗，我并没有看到这方面的介绍，希望能有一个简单的例子？

**Comment by ayanmw** [comment]
我也是很好奇, qiniu/qlang 已经消失,取而代之的是 goplus/gop ，虽然只是重命名，
但是 为什么变化那么大，关键也没有路线图，之前删掉了许多东西，连 qlang.io 这个网址也消失了(404).

以前就想着以后用golang二进制加入一个golang语言的脚本引擎, 现在想去做这件事情了,  看着这个 gop 真是一头雾水啊。

**Comment by ayanmw** [comment]
哎呀, wiki 里面貌似说道了: 
https://github.com/goplus/gop/wiki/History-Version-(qlang)

要去 xushiwei 的仓库，老的qlang 仓库（v1.5分支即可，其他master分支 已经是新的不兼容了）
https://github.com/xushiwei/qlang


不过这个版本号管理，也真是乱啊。。。

**Comment by lx217197** [comment]
> 哎呀, wiki 里面貌似说道了:
> https://github.com/goplus/gop/wiki/History-Version-(qlang)
> 
> 要去 xushiwei 的仓库，老的qlang 仓库（v1.5分支即可，其他master分支 已经是新的不兼容了）
> https://github.com/xushiwei/qlang
> 
> 不过这个版本号管理，也真是乱啊。。。

嗯 我看这个了，我看了其他issue好像gop也能做，qlang应该是不给更了
