### ISSUE TITLE
repl continueMode bug

### ISSUE THREAD

**Issue by RaynorGu** [goplus/gop#744]
![image](https://user-images.githubusercontent.com/7893714/126966507-05c60b23-b0eb-4934-85e4-b153b82ddaaf.png)

Cant input multiline code.

go version
go version go1.14.3 darwin/amd64

os: macOS Catalina 10.5.7

**Comment by xushiwei** [comment]
repl.goplus.org is experimental and not our focus recently.
We are focusing to release Go+ v1.0 version.
