### ISSUE TITLE
goplus 0.9.7 rational number support issue

### ISSUE THREAD

**Issue by qiukeren** [goplus/gop#751]
the playground sample is on main branch,  errors can be reproduced on 0.9.7.

playground 测试代码使用main分支，问题都能使用0.9.7复现。

### 1. Cannot direct print a rational number `3.14r`, directly print `3r` is ok.

无法直接打印`3.14r`，可以直接打印`3r`

https://goplay.qiniu.com/p/valNl8Kgmoe

```
println(3.14r)
```

it panics directly.

![image](https://user-images.githubusercontent.com/2325492/128369184-9204f6be-6163-499f-b6e7-547df43f6100.png)

```
print(3r)
```

### 2. Rational number cannot multiply a integer.

无法和整数直接相乘。

https://goplay.qiniu.com/p/vXcwZIYlkqT
```
x:=3r
x*=2
println(x)
```

it can not convert the type.
![image](https://user-images.githubusercontent.com/2325492/128369264-6a469be1-e2ee-4478-a565-93801279a0dd.png)

### 3. Cannot use the `*=` operator

问题比较类似2，无法使用`*=`之类的运算符来计算，也是因为类型转换的问题。

https://goplay.qiniu.com/p/4l3GbhMZtfF
```
x:=3r
x*=2r
println(x)
```

![image](https://user-images.githubusercontent.com/2325492/128369319-0853c4ed-45b5-46f1-9eff-21687a9eced3.png)

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/commit/57befb41c5a30d52bf6943e5732bd5f8233c6c82
