### ISSUE TITLE
panic: TODO: gop build not impl

### ISSUE THREAD

**Issue by akin520** [goplus/gop#756]
[root@server232 01-Hello-world]# gop build hello.gop 
panic: TODO: gop build not impl

goroutine 1 [running]:
github.com/goplus/gop/cmd/internal/build.runCmd(0x9d1220, 0xc0000a0170, 0x1, 0x1)
        /root/go-mod/gop/cmd/internal/build/build.go:45 +0x39
main.main()
        /root/go-mod/gop/cmd/gop/main.go:93 +0x252

**Comment by xushiwei** [comment]
you can use `gop run` or `gop install` or `gop test`.
