### ISSUE TITLE
cannot define a function after variable definitions

### ISSUE THREAD

**Issue by jxls1992** [goplus/gop#758]
compile code like this，report compilation error :

```
a = 1
func test() {}
```

``` 
GenGoPkg . ...  
main.gop:1:15: expected declaration (and 1 more errors)
```
but compile code like this is ok:

```
func test() {}
a = 1
```

**Comment by xushiwei** [comment]
This is a feature design, not a bug.
Go+ allows to write code without defining a main function. But we don't suggest write code here and there. So we force write global code at the end of a file, and only one file can have global code each package.
