### ISSUE TITLE
packages.Load: gop cache optimization

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#810]
- allow run multi `gop run` instances at the same package.
- increasing pkg load (need to change https://pkg.go.dev/golang.org/x/tools/go/packages#Load)

**Comment by xushiwei** [comment]
We forked [golang.x/tools](https://github.com/golang/tools) to https://github.com/goplus/tools.
You can fix this issue by creating pull request for it.

**Comment by xushiwei** [comment]
I suggest we don't change prototype of `func packages.Load`. We just add a member named `Loaded` for `type packages.Config` (see https://pkg.go.dev/golang.org/x/tools/go/packages#Config):

```go
type Config struct {
    ... // all other members
    Loaded map[string]*Package  // all loaded packages: pkgPath => *Package
}
```

**Comment by kevwan** [comment]
In each `packages.Load` call, patterns might not be `import package`, see [https://github.com/goplus/tools/blob/49ce184b4392a246a1c09b01645277fe676ecc8b/go/packages/golist.go#L170](https://github.com/goplus/tools/blob/49ce184b4392a246a1c09b01645277fe676ecc8b/go/packages/golist.go#L170)

So we cannot use pattern as the key of `Loaded`, and the default method is using `go list` to get detail package informations. Looks we need to get the pkgPath from `go list` results.

For each `packages.Load` call, the result packages are `duduped`.

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v1.1.0-alpha2
