### ISSUE TITLE
gop binary release

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#817]
Requirements:
- make tool (done by @92hackers).
- with std packages (done by @cpunion).
- build for multi platforms (done by @cpunion).
- build with gop env (include VERSION, BUILDREV, etc. done by @92hackers).
- a release tool (for release a new version automatically  #1018).
- a download page like https://go.dev/dl/ (@nighca).
- brew install goplus (done by @cpunion).
- installer for windows and mac (#1019).

Release tool Design (#1018):
- `go run cmd/make.go -tag <Version>`, it will automatically update the `VERSION` file in release branch and create a new tag  named `<Version>`. The release branch of `<Version = vMAJOR.MINOR.PATCH>` is `vMAJOR.MINOR`.

**Comment by CarlJi** [comment]
> It is indeed too troublesome to install now. It would be best to publish an installation package that can be installed with one click.

sure, let's enhance it.

**Comment by CarlJi** [comment]
> Can't get gop of release v1.0.16 run. It got error to run an example script.
> 
> ```
> $ gop run a.gop
> [FATAL] /github/workspace/cmd/internal/run/run.go:91: findGoModFile: no such file or directory
> ```

Currently, please follow [this guide](https://github.com/goplus/gop#how-to-install) to have a try.

**Comment by MirKml** [comment]
> It is indeed too troublesome to install now. It would be best to publish an installation package that can be installed with one click.
Agree. I'm interesting in gop, mostly for "scripting" purposes and have no previous knowledge of go tooling. I'm surprised, that I need to install golang tools to build compiler myself. For some beta version - fine - but gop is in production version 1.1.
