### ISSUE TITLE
New to Gop, faced problem while installing...

### ISSUE THREAD

**Issue by Danny-Yxzl** [goplus/gop#821]
I followed this passage to install gop-environment, but when I was trying to test it, got this error:

```text
E:\Programming\goplus>gop run e:\Programming\goplus\main.gop  
[FATAL] D:/gop/cmd/internal/run/run.go:91: findGoModFile: The system cannot find the file specified.
```

I can hardly find any docs about how to install. What should I do?

Thanks a lot.

**Comment by JessonChan** [comment]
Try this.
```go
cd e:\Programming\goplus\
go mod init goplus
go get github.com/goplus/gop/builtin
gop run main.gop
```

**Comment by xushiwei** [comment]
I add script `all.bash` to simplify install.
see https://github.com/goplus/gop/blob/main/all.bash

**Comment by Danny-Yxzl** [comment]
Strongly thanks to you!
Hope the official-website can add install-guide recently.

I'll close this issue now.
