### ISSUE TITLE
Dont need add gop std packages to go.mod

### ISSUE THREAD

**Issue by xushiwei** [goplus/gop#822]
Now we have to add gop std packages into go.mod:

```bash
go mod download github.com/goplus/gop
```

**Comment by visualfc** [comment]
gop build 时，如果发现需要引入 github.com/goplus/gop/builtin 或其他 github.com/goplus/gop/... 库时，主动在当前项目 go.mod 加入或更新 github.com/goplus/gop 库。
```
go mod edit -require=github.com/goplus/gop@v1.0.12
go mod tidy
```

**Comment by visualfc** [comment]
> > 且需要引用 builtin 时加入
> 
> 这个怎么判断？

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v1.0.36
