### ISSUE TITLE
Download from latest release, but fatal.

### ISSUE THREAD

**Issue by geekgao** [goplus/gop#836]
### What happened?
Download and run a simple example on ubuntu (Amd64).:
```
uname -v 
#35~1630100930~21.04~ae2753e-Ubuntu SMP Mon Aug 30 18:26:54 UTC 
```

```
$./gop run test.gop
[FATAL] /github/workspace/cmd/internal/run/run.go:91: findGoModFile: no such file or directory

```

### What did you expect to happen?

Not should showing any errors

**Comment by CarlJi** [comment]
based on code https://github.com/goplus/gop/blob/main/cmd/internal/run/run.go#L91, `gop run` need to find a proper `go.mod` file, while it may not exist if user didn't clone the code and execute `all.bash`.

we need consider fixing it.

**Comment by geekgao** [comment]
> based on code https://github.com/goplus/gop/blob/main/cmd/internal/run/run.go#L91, `gop run` need to find a proper `go.mod` file, while it may not exist if user didn't clone the code and execute `all.bash`.
> 
> we need consider fixing it.

Yes, need fixing it.
In the promotion phase, it is important to give users clear and convenient instructions. 😄

**Comment by geekgao** [comment]
```
...
github.com/goplus/gop/cmd/internal/gopfmt
github.com/goplus/gop/cmd/internal/help
github.com/goplus/gop/cmd/internal/install
github.com/goplus/gop/cmd/internal/test
github.com/goplus/gop/cmd/internal/run
github.com/goplus/gop/cmd/internal/version
github.com/goplus/gop/cmd/gop
./all.bash: line 12: gop: command not found
```

Execute all.bash, the error. Mabe I should move release package info the directory ?

**Comment by CarlJi** [comment]
> export PATH=$PATH:$(go env GOPATH)/bin

Let's solidify this logic into the script.

**Comment by geekgao** [comment]
> > ```
> > ...
> > github.com/goplus/gop/cmd/internal/gopfmt
> > github.com/goplus/gop/cmd/internal/help
> > github.com/goplus/gop/cmd/internal/install
> > github.com/goplus/gop/cmd/internal/test
> > github.com/goplus/gop/cmd/internal/run
> > github.com/goplus/gop/cmd/internal/version
> > github.com/goplus/gop/cmd/gop
> > ./all.bash: line 12: gop: command not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Execute all.bash, the error. Maybe I should move release package to the directory ?
> 
> `export PATH=$PATH:$(go env GOPATH)/bin`

gop run, it works. But gop build shows:
```
gop build test.gop
2021/10/16 18:01:39 RunGoCmd failed: fork/exec /usr/local/go/bin/go: not a directory
```

**Comment by xushiwei** [comment]
> > > ```
> > > ...
> > > github.com/goplus/gop/cmd/internal/gopfmt
> > > github.com/goplus/gop/cmd/internal/help
> > > github.com/goplus/gop/cmd/internal/install
> > > github.com/goplus/gop/cmd/internal/test
> > > github.com/goplus/gop/cmd/internal/run
> > > github.com/goplus/gop/cmd/internal/version
> > > github.com/goplus/gop/cmd/gop
> > > ./all.bash: line 12: gop: command not found
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Execute all.bash, the error. Maybe I should move release package to the directory ?
> > 
> > 
> > `export PATH=$PATH:$(go env GOPATH)/bin`
> 
> gop run, it works. But gop build shows:
> 
> ```
> gop build test.gop
> 2021/10/16 18:01:39 RunGoCmd failed: fork/exec /usr/local/go/bin/go: not a directory
> ```

@visualfc

**Comment by yermulnik** [comment]
> I suggest you install Go+ from source code.

My comment was not about how to install but about having clear installation instructions both at https://goplus.org/ and https://github.com/goplus/gop/ instead of having no clear instructions with only suggestion being a download link pointing to https://github.com/goplus/gop/releases

**Comment by 92hackers** [comment]
@xushiwei , is there a plan to build a more meaningful doc website, i am willing to help.

**Comment by xushiwei** [comment]
> @xushiwei , is there a plan to build a more meaningful doc website, i am willing to help.

of course.
thx.

**Comment by xushiwei** [comment]
> @xushiwei , is there a plan to build a more meaningful doc website, i am willing to help.

https://github.com/goplus/gop/issues/851
