### ISSUE TITLE
The "How to Build" did not work

### ISSUE THREAD

**Issue by tidwall** [goplus/gop#844]
Hi, I thought you might want to know that the following instructions at https://github.com/goplus/gop#how-to-build:

```
git clone git@github.com:goplus/gop.git
cd gop
./all.bash
```

returns the following error:

```
git@github.com: Permission denied (publickey).
```

But when I do:

```
git clone https://github.com/goplus/gop
cd gop
./all.bash
```

it works.

❤️

**Comment by 92hackers** [comment]
@tidwall, I fixed it, thank you.:smile:
