### ISSUE TITLE
gop run failed at a dir which has `go.mod` file existed.

### ISSUE THREAD

**Issue by 92hackers** [goplus/gop#854]
### The following program `sample.gop` triggers an unexpected result

```coffee
x := 123.1

println(x + 1)
```

### Expected result

```console
124.1
```

### Got

```console
: no required module provides package github.com/goplus/gop/builtin; to add it:
	go get github.com/goplus/gop/builtin
2021/10/24 21:28:04 total 1 errors
panic: total 1 errors
```

### Gop Version

gop devel linux/amd64

### Additional Notes

If i remove `go.mod` file at the target dir, then `gop run` command will successed.

If i readd `go.mod` file and remove auto generated `gop_autogen.go` file, then `gop run` will failed again.

The above experiment should not be run under `gop` repo dir, any other dir which has a `go.mod` file will get such error.

**Comment by damonchen** [comment]
Is it the latest version of gop?  plz, have a try with the latest version?

**Comment by 92hackers** [comment]
Yeah, the latest version of gop.

In order to make `gop run` works,  I have to run `go get github.com/goplus/gop/builtin` to add gop related modules to my project's `go.mod` now.

It's not convenient. 

Maybe the module system of `gop` needs to be enhanced.

**Comment by 92hackers** [comment]
#861 may solve the problem.

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/releases/tag/v1.0.32
