### ISSUE TITLE
Nested function / method definition

### ISSUE THREAD

**Issue by bachue** [goplus/gop#864]
### Proposal

Some private function may only be called by one function. So we hope to make it nested then it will not pollute the package namespace

For example:

```go
import (
	"fmt"
)

func f1() {
	func f2() {
		type F struct{}

		func (f F) f() {
			fmt.Println("F::f()")
		}

		var f F
		f.f()
		fmt.Println("f2()")
	}

	f2()
	fmt.Println("f1()")
}

f1()
// f2()    /* Cannot be called outside the namespace */
```

### Background

Actually in Golang, type could be defined in function, but function cannot. Actually for a big package, there're a huge number of private functions could be defined in many files, and all of them can be called by any file in the package. Sometimes it's very hard to name them, some private function could only be called by one function, and I don't think it should pollute the whole namespace in the package.

### Workarounds

```go
import (
	"fmt"
)

func f1() {
	f2 := func() {
		type F struct{}

		f3 := func(f F) {
			fmt.Println("f3(F)")
		}

		var f F
		f3(f)
		fmt.Println("f2()")
	}

	f2()
	fmt.Println("f1()")
}

f1()
```

**Comment by xushiwei** [comment]
Thx. But we don't want to add such a feature.
