### ISSUE TITLE
when define function before struct define gop say TODO: redefine

### ISSUE THREAD

**Issue by zhangweiii** [goplus/gop#921]
### The following program `sample.gop` triggers an unexpected result

```coffee
func (a A) Say() {
	println "hello ", a.S
}

type A struct {
	S string
}

a := A{
	S: "world",
}

a.Say()
```

### Expected result

```console
hello  world
```

### Got

```console
GenGoPkg .
TODO: redefine
```

### Gop Version

5bc482fd57ba2f422d1ce6baa1a3227a401f51a5

### Additional Notes

[在线运行示例](https://play.goplus.org/p/srhOPuo2VIN)

**Comment by visualfc** [comment]
fixed https://github.com/goplus/gop/pull/920, please update.
